# Generated by Django 4.0.4 on 2022-05-06 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('clientcode', models.CharField(max_length=255, unique=True, verbose_name='Code client')),
                ('societe', models.CharField(blank=True, max_length=255, null=True, verbose_name='Société')),
                ('email', models.EmailField(max_length=255, null=True, unique=True, verbose_name='adresse mail')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('canOrder', models.BooleanField(default=False)),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='Nom')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='Prénom')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Elevage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom ou localisation élévage')),
                ('typ_elevage', models.CharField(choices=[('AVICOL', 'Avicole sauf canard'), ('BOVIN', 'Bovin'), ('CAPRIN', 'Caprin'), ('EQUIN', 'Equin'), ('HELICI', 'Hélicicole'), ('OVIN', 'Ovin'), ('PALMID', 'Palmidés'), ('PORCIN', 'Porcin'), ('DIVERS', 'Divers')], default=None, max_length=6, verbose_name="Type d'élevage")),
                ('valide', models.BooleanField(default=False, verbose_name='Validé')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Crée le')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('chef_elev', models.ManyToManyField(blank=True, related_name='chef_elevage', to=settings.AUTH_USER_MODEL, verbose_name='Chef élevage')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elev_client', to=settings.AUTH_USER_MODEL, verbose_name='client')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit', models.CharField(max_length=255, verbose_name='Nom du produit')),
                ('ref', models.CharField(max_length=255, verbose_name='Référence')),
                ('cat', models.CharField(choices=[('AVICOL', 'Avicole sauf canard'), ('BOVIN', 'Bovin'), ('CAPRIN', 'Caprin'), ('EQUIN', 'Equin'), ('HELICI', 'Hélicicole'), ('OVIN', 'Ovin'), ('PALMID', 'Palmidés'), ('PORCIN', 'Porcin'), ('DIVERS', 'Divers')], default=None, max_length=6, verbose_name="Type d'élevage")),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Crée le')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('date_order', models.DateField(verbose_name='date de commande')),
                ('delivery', models.DateField(verbose_name='Livraison le: ')),
                ('recorded', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_createur', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('elevage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_elevage', to='alim.elevage', verbose_name='Elevage')),
                ('product', models.ManyToManyField(related_name='order_product', to='alim.product', verbose_name='Produit')),
            ],
            options={
                'ordering': ['date_order'],
            },
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(choices=[('FABRIC', 'Fabricant'), ('COMMER', 'Commercial'), ('CLIENT', 'Client'), ('CH_ELE', "Chef d'élevage"), ('CHAUFF', 'Chauffeur')], default='CLIENT', max_length=6, verbose_name='catégorie')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Silo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField(verbose_name='Silo N°')),
                ('contient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produit_silo', to='alim.product', verbose_name='Produit')),
                ('elevage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elevage', to='alim.elevage', verbose_name='Elevage')),
            ],
            options={
                'unique_together': {('number', 'elevage')},
            },
        ),
        migrations.CreateModel(
            name='Chef_elev',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='créateur', to=settings.AUTH_USER_MODEL, verbose_name='créateur')),
            ],
            options={
                'abstract': False,
            },
            bases=('alim.user',),
        ),
    ]
