# Generated by Django 4.0.4 on 2022-05-13 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alim', '0002_telephone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telephone',
            name='phonefix',
        ),
    ]
