# Generated by Django 4.0.4 on 2022-05-13 07:15

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('alim', '0003_remove_telephone_phonefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='telephone',
            name='phonefix',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Tel Fixe'),
        ),
    ]
